# Comentarios
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3307/tienda
db.user=root
db.pass=root


# Configuración del pool
hikari.maximumPoolSize=15
hikari.minimumIdle=2
hikari.connectionTimeout=10000
hikari.idleTimeout=300000
hikari.maxLifetime=600000

